# Generated by Django 6.0.1 on 2026-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='set',
            name='card_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
