# Generated by Django 6.0.1 on 2026-01-26 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_set_slug_alter_card_answer_alter_card_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
