# Generated by Django 6.0.1 on 2026-01-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_set_created_set_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique_for_date='created'),
        ),
    ]
