# Generated by Django 6.0.1 on 2026-01-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_set_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='false_answer1',
            field=models.CharField(default='Wrong Answer', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='false_answer2',
            field=models.CharField(default='Wrong Answer', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='false_answer3',
            field=models.CharField(default='Wrong Answer', max_length=500),
            preserve_default=False,
        ),
    ]
