# Generated by Django 6.0.1 on 2026-01-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_card_false_answer1_card_false_answer2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='false_answer1',
            new_name='false_answer_1',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='false_answer2',
            new_name='false_answer_2',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='false_answer3',
            new_name='false_answer_3',
        ),
    ]
