# Generated by Django 6.0.1 on 2026-01-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_rename_false_answer1_card_false_answer_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='created'),
        ),
    ]
