# Generated by Django 6.0.1 on 2026-02-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_set_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='card_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
